### ISSUE TITLE
Figma updated its file format and the tool no longer works

### ISSUE THREAD

**Issue by yangvw** [yagudaev/figma-to-json#16]

**Comment by yagudaev** [comment]
Hi friends, sorry I've been MIA. Working on fundraising for our startup now, so a bit busy to look at this.

If you fork and create a PR happy to take a look.

.fig file should still be a zip file and inside the zip should be a Kiwi file that is a protocol buffer fork. This: https://github.com/evanw/kiwi

**Comment by harry75369** [comment]
It depends on your needs. If you could accept 3rd-party design format I recommend using our parsing service which support .fig file. See https://vgg.cool/daruma

**Comment by abbott** [comment]
> It depends on your needs. If you could accept 3rd-party design format I recommend using our parsing service which support .fig file. See https://vgg.cool/daruma

Tried it, and and it would be a great if daruma supported elements copied and pasted from figjam into figma. It drops the framed shape objects that have content (e.g., a figjam shape with text inside).

**Comment by rickyzhangca** [comment]
> It depends on your needs. If you could accept 3rd-party design format I recommend using our parsing service which support .fig file. See https://vgg.cool/daruma

much thanks!

**Comment by yagudaev** [comment]
@harry75369, thanks so much for the service recommendation. Looks really cool!

Fixed this issue in #17 thanks for reporting.
