### ISSUE TITLE
Demo files uploading not working

### ISSUE THREAD

**Issue by acuna-public** [yagudaev/figma-to-json#17]
Hi, I'm trying to upload .fig file in live demo, but it doesn't work, drag'n'drop write "Only .fig files", and uploading via selecting file on PC does nothing. What I'm doing wrong? Thanks.

**Comment by lumixraku** [comment]
Same problem.
<img width="663" alt="image" src="https://github.com/yagudaev/figma-to-json/assets/6280941/5d3359d9-1a5c-4b0b-a55a-d0fee20b7f2b">

**Comment by lumixraku** [comment]
I find a solution. Upgrade kiwi-schema version to latest,  the latest is 0.5.0.

**Comment by yagudaev** [comment]
@lumixraku thank you so much for this! It was an easy fix thanks to your comment here 💜
