### ISSUE TITLE
Unable to parse the image properly

### ISSUE THREAD

**Issue by whxcode** [yagudaev/figma-to-json#9]
Hi, I feel that this file is not parsed correctly, can't parse this image?

[fig.zip](https://github.com/yagudaev/figma-to-json/files/9695715/fig.zip)

![image](https://user-images.githubusercontent.com/44012914/193530062-0793b60a-c2da-46cf-8c51-be567993d5a6.png)

@yagudaev

**Comment by whxcode** [comment]
I can't parse the correct image in base64 format through the commandsBlob field.

![image](https://user-images.githubusercontent.com/44012914/193532037-a44f5dae-38ed-4d78-a253-b1ac7f3ddf68.png)

**Comment by yagudaev** [comment]
Hi @whxcode did you solve it?

Sorry for the delay, it's been a crazy week. Landed a new contract and started it and launched a new figma plugin 😁.

**Comment by whxcode** [comment]
> Hi @whxcode did you solve it?
> 
> Sorry for the delay, it's been a crazy week. Landed a new contract and started it and launched a new figma plugin grin.

Well, it has been dealt with. I have time to add it.
